name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2

    # Configurar o Rust
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true

    # Configurar Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Instalar dependências do Python
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pymupdf

    # Configurar Cargo para PyO3
    - name: Install PyO3 dependencies
      run: sudo apt-get install -y python3-dev

    # Construir e testar o projeto
    - name: Build and Test
      run: cargo test
